### PR TITLE
adding tfe_workspace_settings

### PR DESCRIPTION
**Pull request by benjamin-lykins**
Fixes alexbasista/terraform-tfe-workspacer#18

### CODE REVIEW

**Comment by alexbasista** [comment]
Thanks for the PR @benjamin-lykins!  I think to cover our bases it might be good to take this opportunity to default the `execution_mode` input variable value to `null` such that we are honoring whatever the Organization-level Default Execution Mode is set to by default.  I'd want to test this on TFE as well, though (I don't have a TFE instance in front of me at the moment).

**Comment by benjamin-lykins** [comment]
Hey @alexbasista! Made an update to make it null. I did remove the variable validation since the provider will handle that. Let me know if you have thoughts on that. 
```hcl
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Invalid Attribute Value Match
│ 
│   with tfe_workspace_settings.ws,
│   on workspace.tf line 37, in resource "tfe_workspace_settings" "ws":
│   37:   execution_mode = var.execution_mode
│ 
│ Attribute execution_mode value must be one of: ["agent" "local" "remote"], got: "thisdontwork"
```

I thought we had a spare TFE lying around, but it seems like we nuked it at some point. If I get some free time I'll try to spin one up again.

**Review by alexbasista — CHANGES_REQUESTED** [review]
I think this validation condition would actually catch things properly

```
condition     = var.execution_mode != null ? contains(["remote", "local", "agent"], var.execution_mode) : true
```

**Comment by benjamin-lykins** [comment]
Updated with new condition and it catches properly. 

```hcl
╷
│ Error: Invalid value for variable
│ 
│   on variables.tf line 38:
│   38: variable "execution_mode" {
│     ├────────────────
│     │ var.execution_mode is "fail"
│ 
│ If not null, valid values are `remote`, `local`, or `agent`.
│ 
│ This was checked by the validation rule at variables.tf:42,3-13.
╵
```

**Review by alexbasista — APPROVED** [review]

**Pull request merged**
